[development]
address = "localhost"
port = 8000
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8081
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8081
log = "critical"
limits = { forms = 32768 }
